baseURL = 'https://blog.ssb-tech.net/'
languageCode = 'en-us'
title = 'SSB-Tech Blog'
theme = 'm10c'
[params]
  description = "Tales from an angry sysadmin. Follow me as I test out things in my homelab. I may also go on rants occasionally. Sorry about the mess."
  avatar = "author-image.png"
