# This is a basic workflow to help you get started with Actions

name: Publish Blog

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Create the .ssh directory if it does not exist.
        run: mkdir -p "$HOME/.ssh"

      - name: Import SSH private key
        run: |
          echo "$ORACLE_CLOUD_SSH_KEY" > "$HOME/.ssh/id_ed25519"
          chmod 600 $HOME/.ssh/id_ed25519

      - name: Import host into known_hosts file
        run: |
          echo "$ORACLE_CLOUD_KNOWN_HOSTS" > "$HOME/.ssh/known_hosts"
          chmod 600 "$HOME/.ssh/known_hosts"

      - name: Install hugo and build the site.
        run: |
          sudo apt update && sudo apt install hugo -y
          hugo

      - name: SCP the public directory to the remote server.
        run: scp -R -i "$HOME/.ssh/id_ed25519" ./public github@blog.bladewdr.xyz:/var/www/blog.ssb-tech.net

      - name: Clean up .ssh directory.
        run: rm -rf "$HOME/.ssh"


